# header nav
# 菜单路径
menu:
  home: /
  archives: archives
  categories: categories
  tags: tags
  #about: about
  search: search

# site title 
# 页面的标题
# title为空时 Hexo/_config.yml 配置有效
title: 嘎嘣脆鸡肉味

# author profile
# source/imgaes/
# 作者信息
# author为空时 Hexo/_config.yml 配置有效
profile: 
  author: 嘎嘣脆鸡肉味
  avatar: /images/header.jpeg
  description: a nodejs developer

# site favicon
# source/imgaes/
# 站点图标
#favicon: /images/favicon.png

# social link
social:  
  Github: https://github.com/lx1990
  #Weibo:
# Zhihu:
  #Facebook:
  #Twitter:
  #Instagram:
  #LinkedIn:


# toc
# 文章的目录 
toc:
    false

# site analytics 
# 站点访问统计
# [ analytics id ]
#baidu_analytics:
 #636802045446222199ae541e32c8133e
# Google Analytic ID
google_analytics:
 UA-122593838-1
# comment

# disqus(https://disqus.com/)
disqus:
  comment: false
  shortname: lemonreds

# valine(https://github.com/xCss/Valine)
# 创建 leancloud 应用 获取 id|key 填入即可
leancloud:  
  comment: false
  app_id: cFM0eCo0CQ9xmBXmHi1eltol-gzGzoHsz
  app_key: oh9tizsnvV2vNvWgqEvoNtQO

# mob share(http://www.mob.com)
# 文章分享功能
mob_share:
  true

share_item:
- qq
- weixin
- weibo
- douban
- facebook
- twitter
#- tumblr
- google


# donate
# 捐赠功能
# source/imgaes/
donate:
  enable: true
  word: 宠辱不惊,去留无意
  wechat: /images/wechat.png
  alipay: /images/ali.jpeg

# mathjax 
# 渲染LateX公式
# 在post文章头部添加:
#   mathjax: true
# 即可在当前post开启mathjax
mathjax:
  enable: true
  
# excerpt_ignore [boolean]
# increase at the top of your article
# Does this article need to hide the excerpt ?
# 在文章头部中增加此配置 
# 文章是否需要显示摘要 默认为显示

# footer
# 底部信息
footer:
  author: lx
  since: 2018


# theme version
#
version:
  0.3.0